version: '3.8'
services:
  app:
    container_name: app
    image: app

    build: 
      context: .
      # target: app
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - POSTGRES_DB=workstatus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST_AUTH_METHOD=trust 
      - CARGO_NET_GIT_FETCH_WITH_CLI=true
      - DATABASE_URL=postgresql://postgres:12345@db:5432/workstatus
      # - DATABASE_URL=postgresql://postgres:password@db:5432/workstatus
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run build && npm run start"
    mem_limit: 1g  # Limit memory usage to 1GB for the database
    cpus: '1.0'  #

  db:
    container_name: db
    image: postgres:latest
    # build: 
    #   context: .
    #   target: postgres:latest
    ports:
      - "5432:5432"
    # restart: always
      # - DATABASE_URL=postgresql://postgres:12345@db:5432/workstatus
    environment:
      - POSTGRES_DB=workstatus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST_AUTH_METHOD=trust 

      - CARGO_NET_GIT_FETCH_WITH_CLI=true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 1g  # Limit memory usage to 1GB for the database
    cpus: '1.0'  # 

volumes:
  postgres_data: